version: "3.6"

services:
    web:
        build: .
        ports:
            - "8000:8000"
        command: python /app/manage.py runserver 0.0.0.0:8000
        env_file: .env
        depends_on:
            - postgres
        volumes:
            - ./moviemaster:/app
        links:
            - postgres
            - redis
        networks:
            - frontend

    postgres:
        image: postgres:latest
        environment:
            - POSTGRES_USER=moviemaster
            - POSTGRES_DB=moviemaster
            - POSTGRES_PASSWORD=password
        ports:
            - "5432:5432"
        volumes:
            - mmpgdata:/var/lib/postgresql/data
        networks:
            - frontend

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        networks:
            - frontend

volumes:
    mmpgdata:

networks:
    frontend:
        driver: bridge
